# Default values for sample-web-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gmsantos3/sample-web-app
  pullPolicy: Always
  tag: "dev"

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "true"
  hosts:
    - host: webapp.guilhermemsantos.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: tls-guilhermemsantos-dev
     hosts:
       - webapp.guilhermemsantos.dev

resources:
  limits:
    memory: "50Mi"
    cpu: "30m"
  requests:
    memory: "10Mi"
    cpu: "10m"        
