apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/gmsantos3/portfolio-repo/
  ref:
    branch: flux-managed-branch
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/  