name: Build and Push 

on:
  push:
    paths:
      - sample-web-app/app/*
      - sample-web-app/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'sample-web-app/app/*')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        working-directory: sample-web-app
        run: docker build -t gmsantos3/sample-web-app:dev .

      - name: Push Docker image to Docker Hub
        working-directory: sample-web-app
        run: docker push gmsantos3/sample-web-app:dev
